// vue-todo/src/App.vue
<script>
const LS_TAG = "toDos";
let id = 0;
export default {
  data() {
    return {
      text: "",
      toDos: [],
      editing: false,
      editIndex: 0,
    };
  },
  mounted() {
    const stoargeToDos = localStorage.getItem(LS_TAG);
    if (stoargeToDos !== null) {
      this.toDos = JSON.parse(stoargeToDos);
    }
  },
  methods: {
    createToDo() {
      if (this.text !== "") {
        this.toDos.push({ id: id++, text: this.text });
        this.saveToDos();
        this.text = "";
      }
    },
    startEditToDo(toDo) {
      console.log(toDo);
      this.editIndex = toDo.id;
      this.editing = true;
      this.text = this.toDos[toDo.id].text;
    },
    finishEditToDo() {
      this.toDos[this.editIndex].text = this.text;
      this.saveToDos();
      this.editing = false;
      this.text = "";
    },
    deleteToDo(toDo) {
      this.toDos = this.toDos.filter((t) => t !== toDo);
      this.saveToDos();
    },
    saveToDos() {
      localStorage.setItem(LS_TAG, JSON.stringify(this.toDos));
    },
  },
};
</script>

<template>
  <header>
    <h1>To Do Vue!</h1>
  </header>
  <main>
    <form v-if="editing" @submit.prevent="finishEditToDo">
      <h3>Edit to do</h3>
      <input v-model="text" />
    </form>
    <form v-else @submit.prevent="createToDo">
      <h3>Add your to do</h3>
      <input v-model="text" />
    </form>
    <ul>
      <li v-for="toDo in toDos" :key="toDo.id">
        <span>{{ toDo.text }}</span>
        <span @click="startEditToDo(toDo)"> ✏️</span>
        <span @click="deleteToDo(toDo)"> ✅</span>
      </li>
    </ul>
  </main>
</template>

<style></style>

// react-todo/src/App.tsx
import { FormEvent, useEffect, useState } from "react";

const App = () => {
  const [text, setText] = useState("");
  const [toDos, setTodos] = useState([""]);
  const [editing, setEditing] = useState(false);
  const [editIndex, setEditIndex] = useState(0);

  const LS_TAG = "toDos";

  useEffect(() => {
    const stoargeToDos = localStorage.getItem(LS_TAG);
    if (stoargeToDos !== null) {
      setTodos(JSON.parse(stoargeToDos));
    }
  }, []);

  const createToDo = (e: FormEvent) => {
    e.preventDefault();
    if (text !== "") {
      const newToDos = [text, ...toDos];
      saveToDos(newToDos);
      setText("");
    }
  };

  const startEditToDo = (index: number) => {
    setEditIndex(index);
    setEditing(true);
    setText(toDos[index]);
  };

  const finishEditToDo = (e: FormEvent) => {
    e.preventDefault();
    const newToDos = toDos;
    newToDos[editIndex] = text;
    saveToDos(newToDos);
    setEditing(false);
    setText("");
  };

  const deleteToDo = (index: number) => {
    const newToDos = toDos.filter((toDo) => toDo !== toDos[index]);
    saveToDos(newToDos);
  };

  const saveToDos = (newToDos: string[]) => {
    setTodos(newToDos);
    localStorage.setItem(LS_TAG, JSON.stringify(newToDos));
  };

  return (
    <>
      <header>
        <h1>To Do React!</h1>
      </header>
      <main>
        <form onSubmit={editing ? finishEditToDo : createToDo}>
          {editing ? <h3>Edit to do</h3> : <h3>Add your to do</h3>}
          <input
            type="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
        </form>
        <ul>
          {toDos.map((toDo, index) =>
            toDo === "" ? null : (
              <li key={index}>
                <span>{toDo}</span>
                <span onClick={() => startEditToDo(index)}> ✏️</span>
                <span onClick={() => deleteToDo(index)}> ✅</span>
              </li>
            )
          )}
        </ul>
      </main>
    </>
  );
};

export default App;
